### ISSUE TITLE
logout does not work

### ISSUE THREAD

**Issue by TobiasPrt** [mate-app/mate_app#12]
logout does only work after registration, not after sign in

[edit]
there is no logout button

**Comment by TobiasPrt** [comment]
Additional Info:
```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown building Home(dirty, state: _HomeState#998de):
flutter: The getter 'uid' was called on null.
flutter: Receiver: null
flutter: Tried calling: uid
flutter:
flutter: The relevant error-causing widget was:
flutter:   Home file:///Users/tobiaspoertner/Documents/mate_app/lib/views/full_setup/views/login.dart:69:52
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
flutter: #1      UserDataService.document (package:mateapp/services/user_data_service.dart:24:57)
flutter: #2      _HomeState.build (package:mateapp/views/home.dart:84:51)
flutter: #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
flutter: #5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
flutter: #6      Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
flutter: #7      StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
flutter: #8      Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #9      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
flutter: #10     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
flutter: #12     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
flutter: #13     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
flutter: #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
flutter: #20     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
flutter: #21     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
flutter: #22     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
flutter: #23     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #24     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5647:32)
flutter: #25     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
flutter: #26     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
flutter: firebase_crashlytics: Error reported to Crashlytics.
```

**Comment by TobiasPrt** [comment]
#13 removed logout for now
